[theme]
primaryColor = "#00D1FF"
backgroundColor = "#1F1F2E"
secondaryBackgroundColor = "#29293d"
textColor = "#FFFFFF"
font = "sans serif"

[theme.fonts]
bodyFont = "Montserrat"
monoFont = "Roboto Mono"
